services:
  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure:5
    # networks:
    #   - network-db
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notifi}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      TZ: Pacific/Auckland
  sqs:
      image: softwaremill/elasticmq
      container_name: sqs
      restart: on-failure:5
      ports:
        - 9324:9324
        - 9325:9325
      volumes:
        - ./sqs/custom.conf:/opt/elasticmq.conf
        - ./sqs/data:/data
  

# networks:
#   network-db:
#     external: false    
    
