FROM golang:1.22.2
RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app
COPY --chown=app:app backend/go.mod backend/go.sum ./
RUN go mod download

COPY --chown=app:app backend/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/messagedeliveryworker ./cmd/messagedeliveryworker/

CMD ["/app/messagedeliveryworker"]